slogans = [
    'INVEST SMALL AMOUNTS, POTENTIALLY HIGHER RETURNS',
    'FIXED INTEREST RATE ON LOAN PRODUCTS',
    'HIGHLY EVALUATED PROJECTS, REPUTABLE ESCROW SERVICE',
    'MIN. RISK, MAX. RETURN',
    'PROTECT AGAINST ADVERSE MARKET',
    ]
